//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="serRecargaSoap", Namespace="http://tempuri.org/")]
public partial class serRecarga : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetNumeroOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetRecargaOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetSaldoBlOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetSaldoTeOperationCompleted;
    
    /// <remarks/>
    public serRecarga() {
        this.Url = "http://65.167.25.92/wsezetop/serRecarga.asmx";
    }
    
    /// <remarks/>
    public event GetNumeroCompletedEventHandler GetNumeroCompleted;
    
    /// <remarks/>
    public event GetRecargaCompletedEventHandler GetRecargaCompleted;
    
    /// <remarks/>
    public event GetSaldoBlCompletedEventHandler GetSaldoBlCompleted;
    
    /// <remarks/>
    public event GetSaldoTeCompletedEventHandler GetSaldoTeCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetNumero(string strNumSer, string strValRec) {
        object[] results = this.Invoke("GetNumero", new object[] {
                    strNumSer,
                    strValRec});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetNumero(string strNumSer, string strValRec, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetNumero", new object[] {
                    strNumSer,
                    strValRec}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetNumero(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetNumeroAsync(string strNumSer, string strValRec) {
        this.GetNumeroAsync(strNumSer, strValRec, null);
    }
    
    /// <remarks/>
    public void GetNumeroAsync(string strNumSer, string strValRec, object userState) {
        if ((this.GetNumeroOperationCompleted == null)) {
            this.GetNumeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumeroOperationCompleted);
        }
        this.InvokeAsync("GetNumero", new object[] {
                    strNumSer,
                    strValRec}, this.GetNumeroOperationCompleted, userState);
    }
    
    private void OnGetNumeroOperationCompleted(object arg) {
        if ((this.GetNumeroCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetNumeroCompleted(this, new GetNumeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRecarga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetRecarga(string strNumSer, string strValRec, int intNumTie) {
        object[] results = this.Invoke("GetRecarga", new object[] {
                    strNumSer,
                    strValRec,
                    intNumTie});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetRecarga(string strNumSer, string strValRec, int intNumTie, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetRecarga", new object[] {
                    strNumSer,
                    strValRec,
                    intNumTie}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetRecarga(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetRecargaAsync(string strNumSer, string strValRec, int intNumTie) {
        this.GetRecargaAsync(strNumSer, strValRec, intNumTie, null);
    }
    
    /// <remarks/>
    public void GetRecargaAsync(string strNumSer, string strValRec, int intNumTie, object userState) {
        if ((this.GetRecargaOperationCompleted == null)) {
            this.GetRecargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecargaOperationCompleted);
        }
        this.InvokeAsync("GetRecarga", new object[] {
                    strNumSer,
                    strValRec,
                    intNumTie}, this.GetRecargaOperationCompleted, userState);
    }
    
    private void OnGetRecargaOperationCompleted(object arg) {
        if ((this.GetRecargaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetRecargaCompleted(this, new GetRecargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSaldoBl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetSaldoBl() {
        object[] results = this.Invoke("GetSaldoBl", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetSaldoBl(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSaldoBl", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetSaldoBl(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetSaldoBlAsync() {
        this.GetSaldoBlAsync(null);
    }
    
    /// <remarks/>
    public void GetSaldoBlAsync(object userState) {
        if ((this.GetSaldoBlOperationCompleted == null)) {
            this.GetSaldoBlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaldoBlOperationCompleted);
        }
        this.InvokeAsync("GetSaldoBl", new object[0], this.GetSaldoBlOperationCompleted, userState);
    }
    
    private void OnGetSaldoBlOperationCompleted(object arg) {
        if ((this.GetSaldoBlCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetSaldoBlCompleted(this, new GetSaldoBlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSaldoTe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetSaldoTe(string strNumSerInn, string strFecRecInn) {
        object[] results = this.Invoke("GetSaldoTe", new object[] {
                    strNumSerInn,
                    strFecRecInn});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetSaldoTe(string strNumSerInn, string strFecRecInn, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSaldoTe", new object[] {
                    strNumSerInn,
                    strFecRecInn}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetSaldoTe(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetSaldoTeAsync(string strNumSerInn, string strFecRecInn) {
        this.GetSaldoTeAsync(strNumSerInn, strFecRecInn, null);
    }
    
    /// <remarks/>
    public void GetSaldoTeAsync(string strNumSerInn, string strFecRecInn, object userState) {
        if ((this.GetSaldoTeOperationCompleted == null)) {
            this.GetSaldoTeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaldoTeOperationCompleted);
        }
        this.InvokeAsync("GetSaldoTe", new object[] {
                    strNumSerInn,
                    strFecRecInn}, this.GetSaldoTeOperationCompleted, userState);
    }
    
    private void OnGetSaldoTeOperationCompleted(object arg) {
        if ((this.GetSaldoTeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetSaldoTeCompleted(this, new GetSaldoTeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetNumeroCompletedEventHandler(object sender, GetNumeroCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetNumeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetNumeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetRecargaCompletedEventHandler(object sender, GetRecargaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetRecargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetRecargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetSaldoBlCompletedEventHandler(object sender, GetSaldoBlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetSaldoBlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetSaldoBlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetSaldoTeCompletedEventHandler(object sender, GetSaldoTeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetSaldoTeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetSaldoTeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
